# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    #esi: true
    #fragments: true
    php_errors:
        log: true

    workflows:
        advert:
            type: 'state_machine'
            audit_trail:
                enabled: true
            marking_store:
                type: 'method'
                property: 'state'
            supports:
                - App\Entity\Advert
            initial_marking: draft
            places:
                - draft
                - rejected
                - published
            transitions:
                publish:
                    from: draft
                    to:   published
                reject:
                    from: draft
                    to:   rejected
                unpublish:
                    from: published
                    to: rejected    

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
